services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_c
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: expense_tracker

  backend:
    image: maheeshamihiran/expense-backend:latest
    container_name: backend_c
    ports:
      - '4000:4000'
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/expense_tracker
      - JWT_SECRET=expense_tracker_jwt_secret_2024
      - PORT=4000

  frontend:
    image: maheeshamihiran/expense-frontend:latest
    container_name: frontend_c
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  mongodb_data: